FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's/xenial/bionic/g' /etc/apt/sources.list && \
    sed -i '$d' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y \
    wget \
    gcc \
    make \
    gawk \
    libgetopt-argvfile-perl \
    bison \
    git \
    less \
    grep \
    sudo && \
    rm -rf /var/lib/apt/list/*

# Create non-root user
RUN useradd -m how2heap && usermod -aG sudo how2heap

# New added for disable sudo password
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Initilise base user
USER how2heap
WORKDIR /home/how2heap
ENV HOME /home/how2heap

ENV DEBIAN_FRONTEND teletype

# Base command for container
CMD ["/bin/bash"]
