name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: glibc-v${{ matrix.glibc }}
    runs-on: ubuntu-22.04
    steps:
      - name: build tests
        uses: shellphish/how2heap/ci/build@master
        with:
          ubuntu: ${{ matrix.build_ubuntu }}
      - name: run tests
        uses: shellphish/how2heap/ci/test@master
        with:
          ubuntu: ${{ matrix.test_ubuntu }}
          glibc: ${{ matrix.glibc }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - glibc: "2.23"
            build_ubuntu: "16.04"
            test_ubuntu: "16.04"
          - glibc: "2.24"
            build_ubuntu: "16.04"
            test_ubuntu: "16.10"
          - glibc: "2.27"
            build_ubuntu: "18.04"
            test_ubuntu: "18.04"
          - glibc: "2.31"
            build_ubuntu: "20.04"
            test_ubuntu: "20.04"
          - glibc: "2.32"
            build_ubuntu: "20.04"
            test_ubuntu: "20.10"
          - glibc: "2.33"
            build_ubuntu: "20.04"
            test_ubuntu: "21.04"
          - glibc: "2.34"
            build_ubuntu: "20.04"
            test_ubuntu: "21.10"
          - glibc: "2.35"
            build_ubuntu: "22.04"
            test_ubuntu: "22.04"
          - glibc: "2.36"
            build_ubuntu: "22.04"
            test_ubuntu: "22.10"
          - glibc: "2.37"
            build_ubuntu: "22.04"
            test_ubuntu: "23.04"
          - glibc: "2.38"
            build_ubuntu: "22.04"
            test_ubuntu: "23.10"
          - glibc: "2.39"
            build_ubuntu: "24.04"
            test_ubuntu: "24.04"
          - glibc: "2.40"
            build_ubuntu: "24.04"
            test_ubuntu: "24.10"
          - glibc: "2.41"
            build_ubuntu: "24.04"
            test_ubuntu: "25.04"
          - glibc: "2.42"
            build_ubuntu: "24.04"
            test_ubuntu: "25.10"
          - glibc: "2.43"
            build_ubuntu: "24.04"
            test_ubuntu: "26.04"
